AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'holdings-service'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  HoldingService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.handle_event
      Runtime: ruby2.7
      Events:
        CreateHoldingsPath:
          Type: Api
          Properties:
            Path: "/api/v0.1/holdings"
            Method: POST
      Environment:
        Variables:
          PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
          LOG_LEVEL: debug
          DATABASE: holdings
          DB_HOST: docker.for.mac.localhost
          DB_USERNAME: postgres
          DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDASbb0AtfKkNoV46qAIBEIAo2vo+OWx1XryBOr05usabWsLjcHkCpcWWTYiUpojcvZqBoz+KQFYhWQ==
          SCHEMA_STRING: Holding
          STREAM_NAME: Holding-qa
